import json
from pathlib import Path

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
import os

from app.config import Environment
from app.config import config
from app.dependencies import templates
from app.routers import json_api
from app.routers import chart_data

app = FastAPI()

def load_manifest() -> dict:
    """Load manifest generated by vite build."""
    manifest_path = config.static_dir / ".vite" / "manifest.json"
    return json.loads(manifest_path.read_text()) if manifest_path.exists() else {}

# This dir shall be created during development. In production, it is created by vite build command.
config.static_dir.mkdir(exist_ok=True)
app.mount("/static", StaticFiles(directory=config.static_dir), name="static")

app.include_router(json_api.router)
app.include_router(chart_data.router)

@app.get("/", response_class=HTMLResponse)
def homepage(request: Request):
    return templates.TemplateResponse(request=request, name="index.jinja", context={"environment": config.environment, "manifest": load_manifest()})

